name = "dice-football-room"
main = "worker.js"
compatibility_date = "2026-07-01"

[assets]
directory = "public"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "GameRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]

[[durable_objects.bindings]]
name = "LOBBY"
class_name = "Lobby"

[[migrations]]
tag = "v2"
new_sqlite_classes = ["Lobby"]
